/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface user {
  accesses: string[];
  email: string;
  id: string;
  name: string;
  surname: string;
}
